@host = http://localhost:8000

GET {{host}}/profiles/stepvolkov
Access-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzI4MjUzMSwiaWF0IjoxNjU3MjgxOTMxfQ.bQ4BZP-2iyaSwlJrWuT81Owv9IdJZurrbHFa6BpJUjU
Refresh-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzU0MTEzMSwiaWF0IjoxNjU3MjgxOTMxfQ.bzLAtX9BdfnF2IUW1Wyu8PREZMgLNb3KcEU69IkAhIQ
