@host = http://localhost:8000

POST {{host}}/friends
Access-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzI4MzQxMSwiaWF0IjoxNjU3MjgyODExfQ.7MWJH7PSYcqvo6FyjBi-CDZtHla2jvur1JIhDEpsR5Y
Refresh-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzU0MjAxMSwiaWF0IjoxNjU3MjgyODExfQ.iX4MMzIqyR1-GCZ9QgA25JvdzfUCqvmvdJ02qwAzbbs

{
    "leader_username": "otus_teacher"
}
