@host = http://localhost:8000

POST {{host}}/friends
Access-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MiwiVXNlcm5hbWUiOiJvdHVzX3RlYWNoZXIiLCJDcmVhdGVkQXQiOiIyMDIyLTA3LTA4VDEyOjA3OjE4WiIsIkZpcnN0bmFtZSI6IkNvb2wiLCJMYXN0bmFtZSI6IlRlYWNoZXIiLCJCaXJ0aGRhdGUiOiIxOTkwLTA5LTI5VDAwOjAwOjAwWiIsIkdlbmRlciI6Im0iLCJDaXR5SUQiOjEsImlzcyI6InNvY2lhbC1uZXR3b3JrLWF1dGgiLCJleHAiOjE2NTcyODQxNDAsImlhdCI6MTY1NzI4MzU0MH0.8wJ81ZWjdFLGDpxhRgE20FVsC6S6sl9vf89ReM_8BXw
Refresh-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MiwiVXNlcm5hbWUiOiJvdHVzX3RlYWNoZXIiLCJDcmVhdGVkQXQiOiIyMDIyLTA3LTA4VDEyOjA3OjE4WiIsIkZpcnN0bmFtZSI6IkNvb2wiLCJMYXN0bmFtZSI6IlRlYWNoZXIiLCJCaXJ0aGRhdGUiOiIxOTkwLTA5LTI5VDAwOjAwOjAwWiIsIkdlbmRlciI6Im0iLCJDaXR5SUQiOjEsImlzcyI6InNvY2lhbC1uZXR3b3JrLWF1dGgiLCJleHAiOjE2NTc1NDI3NDAsImlhdCI6MTY1NzI4MzU0MH0.IaPK0nIfEzcO5cVrg17XfAhfbwjMFJduVDNhfsjUvGE

{
    "leader_username": "stepvolkov"
}
