@host = http://localhost:8000

GET {{host}}/friends/stepvolkov
Access-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzI4NDEwNywiaWF0IjoxNjU3MjgzNTA3fQ.ARQl1_YcOLTPpp63MB_pi7e6p9cO2dxqGUoWovb2RTE
Refresh-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiVXNlcm5hbWUiOiJzdGVwdm9sa292IiwiQ3JlYXRlZEF0IjoiMjAyMi0wNy0wOFQxMjowNToyMFoiLCJGaXJzdG5hbWUiOiJTdGVwYW4iLCJMYXN0bmFtZSI6IlZvbGtvdiIsIkJpcnRoZGF0ZSI6IjE5OTYtMDktMjlUMDA6MDA6MDBaIiwiR2VuZGVyIjoibSIsIkNpdHlJRCI6MywiaXNzIjoic29jaWFsLW5ldHdvcmstYXV0aCIsImV4cCI6MTY1NzU0MjcwNywiaWF0IjoxNjU3MjgzNTA3fQ.0-b6Y1bmVEpdIImwgsQOTJcaUD0jgBIjKgWjg6m6KyQ
