version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'social-network'
      MYSQL_USER: 'social-network-srv'
      MYSQL_PASSWORD: '1qaz'
      MYSQL_ROOT_PASSWORD: '1qaz@WSX'
    ports:
      - '3306:3306'

  userapi:
    image: stepan2volkov/userapi
    build:
      context: userapi
    restart: always
    environment:
      DSN: 'social-network-srv:1qaz@tcp(db:3306)/social-network?parseTime=true'
    ports:
      - '8000:8000'
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana/:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
