name: Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Lint
      uses: make lint
#    - name: Test
#      run: make test
#    - name: Test Race
#      run: make test-race
